name: CI/CD Pipeline

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install black pylint mypy pytest pytest-cov
        # awscli
        
    - name: Format with black
      run: |
        black . --check
        
    - name: Lint with pylint
      run: |
        pylint --disable=C0111,C0103,W0611,W0621,W0613,W0105 $(git ls-files '*.py')
        
    - name: Check types with mypy
      run: |
        mypy .
        
    - name: Test with pytest
      run: |
        pytest --cov=./ --cov-report=xml
